// This file is auto-generated by mockupPreviewPlugin.ts.
type ModuleMap = Record<string, () => Promise<Record<string, unknown>>>;
export const modules: ModuleMap = {
  "./components/mockups/admin-design/DarkSlate.tsx": () => import("../components/mockups/admin-design/DarkSlate.tsx"),
  "./components/mockups/admin-design/LightBlue.tsx": () => import("../components/mockups/admin-design/LightBlue.tsx"),
  "./components/mockups/admin-design/NeutralOdoo.tsx": () => import("../components/mockups/admin-design/NeutralOdoo.tsx")
};
